# Generated by Django 4.0.6 on 2024-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WACGetData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='numerical_data',
            field=models.JSONField(default=dict),
        ),
    ]
