# Generated by Django 4.0.6 on 2024-08-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WACGetData', '0003_alter_persondata_numerical_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='numerical_data',
            new_name='cal_data',
        ),
    ]
