# Generated by Django 5.2.11 on 2026-02-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WACGetData', '0004_rename_numerical_data_persondata_cal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
                ('value3', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PersonData',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='WACGetData.userprofile'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'date'], name='WACGetData__user_id_195a0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('date', 'user', 'time')},
        ),
    ]
