# Generated by Django 4.2.28 on 2026-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WACGetData", "0005_dailyentry_userprofile_delete_persondata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyentry",
            name="value3",
            field=models.FloatField(),
        ),
    ]
