# Generated by Django 6.0.2 on 2026-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WACGetData", "0007_phonenumbermapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyentry",
            name="current_calories",
            field=models.FloatField(
                blank=True,
                help_text="Sum of all calories for this day before this entry",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calories_needed",
            field=models.FloatField(
                blank=True,
                help_text="Total calories needed to achieve desired weight",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="desired_weight",
            field=models.FloatField(
                blank=True, help_text="Target weight in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_carbs",
            field=models.FloatField(
                blank=True, help_text="Target carbs in grams per day", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_fat",
            field=models.FloatField(
                blank=True, help_text="Target fat in grams per day", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_protein",
            field=models.FloatField(
                blank=True, help_text="Target protein in grams per day", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Current weight in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight_last_updated",
            field=models.DateField(
                blank=True, help_text="Date when weight was last updated", null=True
            ),
        ),
    ]
